# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_server_id', models.CharField(max_length=255)),
                ('squad_url', models.CharField(max_length=255)),
            ],
        ),
    ]
