# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180103_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='discord_server_id',
            field=models.CharField(default=201723355282276352, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='duration',
            field=models.CharField(default=7, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='discord_server_id',
            field=models.CharField(default=201723355282276352, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='discord_server_id',
            field=models.CharField(default=201723355282276352, max_length=255),
            preserve_default=False,
        ),
    ]
