# Generated by Django 2.0.1 on 2018-01-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180103_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='display_name',
        ),
    ]
