# Generated by Django 2.0.1 on 2018-01-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_player_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='tite',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='tite',
            new_name='title',
        ),
    ]
