# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180104_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraward',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
