# Generated by Django 2.0.6 on 2018-11-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180202_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wt_nick',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
