# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-26 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_wt_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='duration',
        ),
    ]
