# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_award_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
