# Generated by Django 4.0.5 on 2023-02-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_award_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='discord_server_id',
            new_name='guild_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='discord_server_id',
            new_name='guild_id',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='discord_server_id',
            new_name='guild_id',
        ),
    ]
