# Generated by Django 4.0.5 on 2023-02-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_discord_server_id_award_guild_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='discord_id',
            new_name='user_id',
        ),
    ]
