# Generated by Django 4.0.5 on 2023-09-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_discord_id_player_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
